_id: 81c4f770-b528-11ea-babb-bf895c22efb2
_parent: 'https://yasoob.me/posts/nike-run-club-data-visualization/'
name: JB
email: 27e1cb03def5ec88c5cb01471b536159
reply_to: f42f40e0-1a1e-11ea-bab8-ddd12236f0d2
comment: "I receive the same error when I try to run this code in Python3:\r\n'{\"error_id\":\"a4f7e2d8-6c5e-4f98-8964-c00cd96fb5d3\",\"errors\":[{\"code\":35,\"message\":\"Unauthorized user access\"}]}'\r\n\r\nI am most likely not setting up something correctly.\r\n\r\nimport pycurl\r\nimport certifi\r\nfrom io import BytesIO\r\n\r\nbuffer = BytesIO()\r\nheader = ['Authorization', 'Bearer eyJhbGciOiJSUzI........']\r\nurl = 'https://api.nike.com/sport/v3/me/activities/after_time/0'\r\n\r\nc = pycurl.Curl()\r\nc.setopt(c.CAINFO, certifi.where())\r\nc.setopt(c.URL, url)\r\nc.setopt(c.HTTPHEADER, header)  \r\nc.setopt(c.WRITEDATA, buffer)\r\n\r\nc.perform()\r\nc.close()\r\n\r\nbody = buffer.getvalue()\r\nprint(body)"
name_try: ''
date: '2020-06-23T08:06:57.014Z'
