_id: !!python/unicode '12727'
comment: !!python/unicode 'I get it, I just don''t understand why the print statement
  was never executed when you called x.bankrupt. Seems to me that if the value of
  x.bankrupt is false, then the branch is open and the call to print should be executed.
  Am I missing something?'
date: !!python/unicode '2017-11-09 04:28:27'
email: 43aa4f25230092eeeffe34de3abad8e7
name: !!python/unicode 'D'
